/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as DireitoTributarioRouteImport } from './routes/direito-tributario'
import { Route as DireitoImobiliarioRouteImport } from './routes/direito-imobiliario'
import { Route as DireitoEmpresarialRouteImport } from './routes/direito-empresarial'
import { Route as DireitoDoConsumidorRouteImport } from './routes/direito-do-consumidor'
import { Route as DireitoDeFamiliaRouteImport } from './routes/direito-de-familia'
import { Route as DireitoContratosRouteImport } from './routes/direito-contratos'
import { Route as DireitoCivilRouteImport } from './routes/direito-civil'
import { Route as ConsultoriaJuridicaRouteImport } from './routes/consultoria-juridica'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoTributarioRoute = DireitoTributarioRouteImport.update({
  id: '/direito-tributario',
  path: '/direito-tributario',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoImobiliarioRoute = DireitoImobiliarioRouteImport.update({
  id: '/direito-imobiliario',
  path: '/direito-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoEmpresarialRoute = DireitoEmpresarialRouteImport.update({
  id: '/direito-empresarial',
  path: '/direito-empresarial',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoDoConsumidorRoute = DireitoDoConsumidorRouteImport.update({
  id: '/direito-do-consumidor',
  path: '/direito-do-consumidor',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoDeFamiliaRoute = DireitoDeFamiliaRouteImport.update({
  id: '/direito-de-familia',
  path: '/direito-de-familia',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoContratosRoute = DireitoContratosRouteImport.update({
  id: '/direito-contratos',
  path: '/direito-contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoCivilRoute = DireitoCivilRouteImport.update({
  id: '/direito-civil',
  path: '/direito-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaJuridicaRoute = ConsultoriaJuridicaRouteImport.update({
  id: '/consultoria-juridica',
  path: '/consultoria-juridica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultoria-juridica': typeof ConsultoriaJuridicaRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-contratos': typeof DireitoContratosRoute
  '/direito-de-familia': typeof DireitoDeFamiliaRoute
  '/direito-do-consumidor': typeof DireitoDoConsumidorRoute
  '/direito-empresarial': typeof DireitoEmpresarialRoute
  '/direito-imobiliario': typeof DireitoImobiliarioRoute
  '/direito-tributario': typeof DireitoTributarioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultoria-juridica': typeof ConsultoriaJuridicaRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-contratos': typeof DireitoContratosRoute
  '/direito-de-familia': typeof DireitoDeFamiliaRoute
  '/direito-do-consumidor': typeof DireitoDoConsumidorRoute
  '/direito-empresarial': typeof DireitoEmpresarialRoute
  '/direito-imobiliario': typeof DireitoImobiliarioRoute
  '/direito-tributario': typeof DireitoTributarioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultoria-juridica': typeof ConsultoriaJuridicaRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-contratos': typeof DireitoContratosRoute
  '/direito-de-familia': typeof DireitoDeFamiliaRoute
  '/direito-do-consumidor': typeof DireitoDoConsumidorRoute
  '/direito-empresarial': typeof DireitoEmpresarialRoute
  '/direito-imobiliario': typeof DireitoImobiliarioRoute
  '/direito-tributario': typeof DireitoTributarioRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultoria-juridica'
    | '/direito-civil'
    | '/direito-contratos'
    | '/direito-de-familia'
    | '/direito-do-consumidor'
    | '/direito-empresarial'
    | '/direito-imobiliario'
    | '/direito-tributario'
    | '/politica-privacidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultoria-juridica'
    | '/direito-civil'
    | '/direito-contratos'
    | '/direito-de-familia'
    | '/direito-do-consumidor'
    | '/direito-empresarial'
    | '/direito-imobiliario'
    | '/direito-tributario'
    | '/politica-privacidade'
  id:
    | '__root__'
    | '/'
    | '/consultoria-juridica'
    | '/direito-civil'
    | '/direito-contratos'
    | '/direito-de-familia'
    | '/direito-do-consumidor'
    | '/direito-empresarial'
    | '/direito-imobiliario'
    | '/direito-tributario'
    | '/politica-privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultoriaJuridicaRoute: typeof ConsultoriaJuridicaRoute
  DireitoCivilRoute: typeof DireitoCivilRoute
  DireitoContratosRoute: typeof DireitoContratosRoute
  DireitoDeFamiliaRoute: typeof DireitoDeFamiliaRoute
  DireitoDoConsumidorRoute: typeof DireitoDoConsumidorRoute
  DireitoEmpresarialRoute: typeof DireitoEmpresarialRoute
  DireitoImobiliarioRoute: typeof DireitoImobiliarioRoute
  DireitoTributarioRoute: typeof DireitoTributarioRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-tributario': {
      id: '/direito-tributario'
      path: '/direito-tributario'
      fullPath: '/direito-tributario'
      preLoaderRoute: typeof DireitoTributarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-imobiliario': {
      id: '/direito-imobiliario'
      path: '/direito-imobiliario'
      fullPath: '/direito-imobiliario'
      preLoaderRoute: typeof DireitoImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-empresarial': {
      id: '/direito-empresarial'
      path: '/direito-empresarial'
      fullPath: '/direito-empresarial'
      preLoaderRoute: typeof DireitoEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-do-consumidor': {
      id: '/direito-do-consumidor'
      path: '/direito-do-consumidor'
      fullPath: '/direito-do-consumidor'
      preLoaderRoute: typeof DireitoDoConsumidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-de-familia': {
      id: '/direito-de-familia'
      path: '/direito-de-familia'
      fullPath: '/direito-de-familia'
      preLoaderRoute: typeof DireitoDeFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-contratos': {
      id: '/direito-contratos'
      path: '/direito-contratos'
      fullPath: '/direito-contratos'
      preLoaderRoute: typeof DireitoContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-civil': {
      id: '/direito-civil'
      path: '/direito-civil'
      fullPath: '/direito-civil'
      preLoaderRoute: typeof DireitoCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria-juridica': {
      id: '/consultoria-juridica'
      path: '/consultoria-juridica'
      fullPath: '/consultoria-juridica'
      preLoaderRoute: typeof ConsultoriaJuridicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultoriaJuridicaRoute: ConsultoriaJuridicaRoute,
  DireitoCivilRoute: DireitoCivilRoute,
  DireitoContratosRoute: DireitoContratosRoute,
  DireitoDeFamiliaRoute: DireitoDeFamiliaRoute,
  DireitoDoConsumidorRoute: DireitoDoConsumidorRoute,
  DireitoEmpresarialRoute: DireitoEmpresarialRoute,
  DireitoImobiliarioRoute: DireitoImobiliarioRoute,
  DireitoTributarioRoute: DireitoTributarioRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
